// Import local images
import burger from "../assets/FeaturedImages/burger.png";
import yuzu from "../assets/FeaturedImages/yuzu.png";
import pizza from "../assets/FeaturedImages/pizza.png";
import cake from "../assets/FeaturedImages/cake.png";

const Dishes = [
  {
    id: 31,
    image: burger,
    name: "Artisan Truffle Burger",
    description:
      "Wagyu beef patty, black truffle aioli, aged gruyere, brioche bun.",
    price: 24,
    rating: 4.9,
    cuisine: "American",
    caloriesPerServing: 750,
    prepTime: "15 mins",
    calories: "750 Kcal",
    isFeatured: true,
    ingredients: [
      "Wagyu Beef Patty",
      "Black Truffle Aioli",
      "Aged Gruyere Cheese",
      "Caramelized Onions",
      "Fresh Arugula",
      "Artisanal Brioche Bun",
    ],
  },
  {
    id: 32,
    image: yuzu,
    name: "Yuzu Salmon Bowl",
    description:
      "Fresh Atlantic salmon, edamame, avocado, yuzu ponzu dressing.",
    price: 22.5,
    rating: 4.8,
    cuisine: "Japanese",
    caloriesPerServing: 580,
    prepTime: "20 mins",
    calories: "580 Kcal",
    isFeatured: true,
    ingredients: [
      "Atlantic Salmon",
      "Edamame",
      "Avocado",
      "Yuzu Ponzu Dressing",
      "Sushi Rice",
      "Nori Seaweed",
      "Sesame Seeds",
    ],
  },
  {
    id: 33,
    image: pizza,
    name: "Wood-Fired Margherita",
    description:
      "San Marzano tomatoes, buffalo mozzarella, fresh basil, olive oil.",
    price: 18,
    rating: 4.9,
    cuisine: "Italian",
    caloriesPerServing: 620,
    prepTime: "12 mins",
    calories: "620 Kcal",
    isFeatured: true,
    ingredients: [
      "San Marzano Tomatoes",
      "Buffalo Mozzarella",
      "Fresh Basil",
      "Extra Virgin Olive Oil",
      "Wood-Fired Crust",
      "Garlic",
      "Sea Salt",
    ],
  },
  {
    id: 34,
    image: cake,
    name: "Molten Chocolate Cake",
    description:
      "Valrhona dark chocolate, vanilla bean ice cream, raspberry coulis.",
    price: 12.5,
    rating: 4.7,
    cuisine: "Dessert",
    caloriesPerServing: 480,
    prepTime: "10 mins",
    calories: "480 Kcal",
    isFeatured: true,
    ingredients: [
      "Valrhona Dark Chocolate",
      "Vanilla Bean Ice Cream",
      "Raspberry Coulis",
      "Butter",
      "Sugar",
      "Eggs",
      "Flour",
      "Fresh Raspberries",
    ],
  },

  {
    id: 35,
    image:
      "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=600&q=80",
    name: "Lobster Thermidor",
    description: "Butter-poached lobster, brandy cream sauce, gruyere crust.",
    price: 58,
    rating: 4.9,
    cuisine: "French",
    caloriesPerServing: 640,
    prepTime: "35 mins",
    calories: "640 Kcal",
    isFeatured: true,
    ingredients: [
      "Lobster",
      "Brandy",
      "Heavy Cream",
      "Gruyere",
      "Dijon Mustard",
      "Tarragon",
    ],
  },
  {
    id: 36,
    image:
      "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80",
    name: "Chicken Tikka Masala",
    description:
      "Tandoori chicken in creamy spiced tomato sauce with basmati rice.",
    price: 19.5,
    rating: 4.8,
    cuisine: "Indian",
    caloriesPerServing: 610,
    prepTime: "30 mins",
    calories: "610 Kcal",
    isFeatured: true,
    ingredients: [
      "Chicken",
      "Tomato Puree",
      "Heavy Cream",
      "Garam Masala",
      "Ginger",
      "Garlic",
      "Basmati Rice",
    ],
  },
  {
    id: 37,
    image:
      "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=600&q=80",
    name: "Beef Pho",
    description:
      "Vietnamese rice noodle soup, slow-simmered beef broth, herbs.",
    price: 16,
    rating: 4.8,
    cuisine: "Vietnamese",
    caloriesPerServing: 520,
    prepTime: "40 mins",
    calories: "520 Kcal",
    isFeatured: true,
    ingredients: [
      "Rice Noodles",
      "Beef Brisket",
      "Star Anise",
      "Cinnamon",
      "Fresh Basil",
      "Bean Sprouts",
      "Lime",
    ],
  },
  {
    id: 38,
    image:
      "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?w=600&q=80",
    name: "Lamb Tagine",
    description: "Slow-cooked Moroccan lamb, apricots, almonds, couscous.",
    price: 27,
    rating: 4.7,
    cuisine: "Moroccan",
    caloriesPerServing: 680,
    prepTime: "45 mins",
    calories: "680 Kcal",
    isFeatured: true,
    ingredients: [
      "Lamb Shoulder",
      "Dried Apricots",
      "Almonds",
      "Cumin",
      "Coriander",
      "Couscous",
    ],
  },
  {
    id: 39,
    image:
      "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&q=80",
    name: "Pad Thai",
    description: "Stir-fried rice noodles, shrimp, tamarind, peanuts, lime.",
    price: 17,
    rating: 4.8,
    cuisine: "Thai",
    caloriesPerServing: 590,
    prepTime: "20 mins",
    calories: "590 Kcal",
    isFeatured: true,
    ingredients: [
      "Rice Noodles",
      "Shrimp",
      "Tamarind",
      "Fish Sauce",
      "Peanuts",
      "Egg",
      "Bean Sprouts",
    ],
  },
  {
    id: 40,
    image:
      "https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=600&q=80",
    name: "Seafood Paella",
    description: "Saffron rice with mussels, shrimp, calamari, and chorizo.",
    price: 34,
    rating: 4.9,
    cuisine: "Spanish",
    caloriesPerServing: 720,
    prepTime: "50 mins",
    calories: "720 Kcal",
    isFeatured: true,
    ingredients: [
      "Bomba Rice",
      "Saffron",
      "Mussels",
      "Shrimp",
      "Calamari",
      "Chorizo",
      "Bell Peppers",
    ],
  },
  {
    id: 41,
    image:
      "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600&q=80",
    name: "Beef Wellington",
    description: "Filet mignon wrapped in puff pastry with mushroom duxelles.",
    price: 62,
    rating: 5.0,
    cuisine: "British",
    caloriesPerServing: 810,
    prepTime: "60 mins",
    calories: "810 Kcal",
    isFeatured: true,
    ingredients: [
      "Filet Mignon",
      "Puff Pastry",
      "Mushroom Duxelles",
      "Prosciutto",
      "Dijon Mustard",
    ],
  },
  {
    id: 42,
    image:
      "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&q=80",
    name: "Butter Chicken",
    description: "Creamy tomato-butter sauce with tender tandoori chicken.",
    price: 20,
    rating: 4.8,
    cuisine: "Indian",
    caloriesPerServing: 630,
    prepTime: "35 mins",
    calories: "630 Kcal",
    isFeatured: true,
    ingredients: [
      "Chicken",
      "Butter",
      "Tomato Puree",
      "Heavy Cream",
      "Fenugreek",
      "Garam Masala",
    ],
  },
  {
    id: 43,
    image:
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80",
    name: "Sushi Platter",
    description:
      "Assorted nigiri and maki rolls with wasabi and pickled ginger.",
    price: 38,
    rating: 4.9,
    cuisine: "Japanese",
    caloriesPerServing: 540,
    prepTime: "30 mins",
    calories: "540 Kcal",
    isFeatured: true,
    ingredients: [
      "Sushi Rice",
      "Salmon",
      "Tuna",
      "Yellowtail",
      "Nori",
      "Wasabi",
      "Pickled Ginger",
    ],
  },
  {
    id: 44,
    image:
      "https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=600&q=80",
    name: "Duck à l'Orange",
    description: "Roasted duck breast, orange gastrique, seasonal vegetables.",
    price: 44,
    rating: 4.8,
    cuisine: "French",
    caloriesPerServing: 690,
    prepTime: "45 mins",
    calories: "690 Kcal",
    isFeatured: true,
    ingredients: [
      "Duck Breast",
      "Orange",
      "Grand Marnier",
      "Butter",
      "Thyme",
      "Root Vegetables",
    ],
  },
  {
    id: 45,
    image:
      "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600&q=80",
    name: "Greek Moussaka",
    description: "Layered eggplant, spiced lamb, béchamel, baked golden.",
    price: 23,
    rating: 4.7,
    cuisine: "Greek",
    caloriesPerServing: 660,
    prepTime: "55 mins",
    calories: "660 Kcal",
    isFeatured: true,
    ingredients: [
      "Eggplant",
      "Ground Lamb",
      "Béchamel",
      "Tomato",
      "Cinnamon",
      "Parmesan",
    ],
  },
  {
    id: 46,
    image:
      "https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=600&q=80",
    name: "Korean Bibimbap",
    description: "Rice bowl with bulgogi beef, vegetables, egg, gochujang.",
    price: 21,
    rating: 4.8,
    cuisine: "Korean",
    caloriesPerServing: 620,
    prepTime: "25 mins",
    calories: "620 Kcal",
    isFeatured: true,
    ingredients: [
      "Rice",
      "Bulgogi Beef",
      "Spinach",
      "Carrots",
      "Egg",
      "Gochujang",
      "Sesame Oil",
    ],
  },
  {
    id: 47,
    image:
      "https://images.unsplash.com/photo-1579208575657-c595a05383b7?w=600&q=80",
    name: "Fish & Chips",
    description: "Beer-battered cod, triple-cooked chips, tartar sauce.",
    price: 19,
    rating: 4.6,
    cuisine: "British",
    caloriesPerServing: 780,
    prepTime: "25 mins",
    calories: "780 Kcal",
    isFeatured: true,
    ingredients: [
      "Cod Fillet",
      "Beer Batter",
      "Potatoes",
      "Tartar Sauce",
      "Peas",
      "Malt Vinegar",
    ],
  },
  {
    id: 48,
    image:
      "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&q=80",
    name: "Chicken Shawarma",
    description:
      "Marinated chicken wrap, garlic sauce, pickles, fresh veggies.",
    price: 14,
    rating: 4.7,
    cuisine: "Lebanese",
    caloriesPerServing: 550,
    prepTime: "20 mins",
    calories: "550 Kcal",
    isFeatured: true,
    ingredients: [
      "Chicken Thighs",
      "Pita Bread",
      "Garlic Sauce",
      "Pickles",
      "Tomato",
      "Lettuce",
      "Sumac",
    ],
  },
  {
    id: 49,
    image:
      "https://images.unsplash.com/photo-1580651315530-69c8e0026377?w=600&q=80",
    name: "Beef Bulgogi",
    description: "Marinated grilled beef, sesame, scallions, steamed rice.",
    price: 25,
    rating: 4.9,
    cuisine: "Korean",
    caloriesPerServing: 640,
    prepTime: "30 mins",
    calories: "640 Kcal",
    isFeatured: true,
    ingredients: [
      "Beef Ribeye",
      "Soy Sauce",
      "Sesame Oil",
      "Pear",
      "Garlic",
      "Scallions",
      "Rice",
    ],
  },
  {
    id: 50,
    image:
      "https://images.unsplash.com/photo-1587740908075-9e245070dfaa?w=600&q=80",
    name: "Gnocchi Sorrentina",
    description: "Potato gnocchi, San Marzano tomato, mozzarella, basil.",
    price: 18.5,
    rating: 4.7,
    cuisine: "Italian",
    caloriesPerServing: 590,
    prepTime: "25 mins",
    calories: "590 Kcal",
    isFeatured: true,
    ingredients: [
      "Potato Gnocchi",
      "Tomato Sauce",
      "Mozzarella",
      "Basil",
      "Parmesan",
      "Olive Oil",
    ],
  },
  {
    id: 51,
    image:
      "https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=600&q=80",
    name: "Peking Duck",
    description: "Crispy roasted duck, pancakes, hoisin, scallions, cucumber.",
    price: 55,
    rating: 4.9,
    cuisine: "Chinese",
    caloriesPerServing: 720,
    prepTime: "90 mins",
    calories: "720 Kcal",
    isFeatured: true,
    ingredients: [
      "Duck",
      "Mandarin Pancakes",
      "Hoisin Sauce",
      "Scallions",
      "Cucumber",
      "Five-Spice",
    ],
  },
  {
    id: 52,
    image:
      "https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?w=600&q=80",
    name: "Ceviche",
    description: "Fresh sea bass cured in lime, red onion, cilantro, aji.",
    price: 20,
    rating: 4.8,
    cuisine: "Peruvian",
    caloriesPerServing: 320,
    prepTime: "20 mins",
    calories: "320 Kcal",
    isFeatured: true,
    ingredients: [
      "Sea Bass",
      "Lime Juice",
      "Red Onion",
      "Cilantro",
      "Aji Amarillo",
      "Sweet Potato",
      "Corn",
    ],
  },
  {
    id: 53,
    image:
      "https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?w=600&q=80",
    name: "Ratatouille",
    description: "Provençal vegetable stew, herbes de Provence, olive oil.",
    price: 16,
    rating: 4.6,
    cuisine: "French",
    caloriesPerServing: 340,
    prepTime: "40 mins",
    calories: "340 Kcal",
    isFeatured: true,
    ingredients: [
      "Eggplant",
      "Zucchini",
      "Bell Pepper",
      "Tomato",
      "Onion",
      "Herbes de Provence",
    ],
  },
  {
    id: 54,
    image:
      "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=600&q=80",
    name: "Jollof Rice",
    description: "West African spiced rice, tomato base, served with chicken.",
    price: 17,
    rating: 4.8,
    cuisine: "Nigerian",
    caloriesPerServing: 620,
    prepTime: "45 mins",
    calories: "620 Kcal",
    isFeatured: true,
    ingredients: [
      "Long-Grain Rice",
      "Tomato",
      "Pepper",
      "Onion",
      "Chicken",
      "Thyme",
      "Bay Leaf",
    ],
  },
  {
    id: 55,
    image:
      "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80",
    name: "Tiramisu",
    description: "Espresso-soaked ladyfingers, mascarpone, cocoa dust.",
    price: 11,
    rating: 4.9,
    cuisine: "Dessert",
    caloriesPerServing: 420,
    prepTime: "20 mins",
    calories: "420 Kcal",
    isFeatured: true,
    ingredients: [
      "Ladyfingers",
      "Mascarpone",
      "Espresso",
      "Cocoa",
      "Eggs",
      "Sugar",
    ],
  },
  {
    id: 56,
    image:
      "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=600&q=80",
    name: "Crème Brûlée",
    description: "Vanilla bean custard with caramelized sugar crust.",
    price: 10.5,
    rating: 4.9,
    cuisine: "Dessert",
    caloriesPerServing: 380,
    prepTime: "15 mins",
    calories: "380 Kcal",
    isFeatured: true,
    ingredients: ["Heavy Cream", "Vanilla Bean", "Egg Yolks", "Sugar"],
  },
  {
    id: 57,
    image:
      "https://images.unsplash.com/photo-1568909344668-6f14a07b56a0?w=600&q=80",
    name: "Mango Sticky Rice",
    description: "Thai sweet sticky rice, coconut cream, fresh mango.",
    price: 9.5,
    rating: 4.7,
    cuisine: "Thai",
    caloriesPerServing: 350,
    prepTime: "30 mins",
    calories: "350 Kcal",
    isFeatured: true,
    ingredients: [
      "Glutinous Rice",
      "Coconut Milk",
      "Mango",
      "Sugar",
      "Sesame Seeds",
    ],
  },
  {
    id: 58,
    image:
      "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=600&q=80",
    name: "Shakshuka",
    description: "Poached eggs in spiced tomato and pepper sauce, feta.",
    price: 14,
    rating: 4.6,
    cuisine: "Middle Eastern",
    caloriesPerServing: 410,
    prepTime: "25 mins",
    calories: "410 Kcal",
    isFeatured: true,
    ingredients: [
      "Eggs",
      "Tomato",
      "Bell Pepper",
      "Onion",
      "Cumin",
      "Paprika",
      "Feta",
    ],
  },
  {
    id: 59,
    image:
      "https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?w=600&q=80",
    name: "Lobster Roll",
    description: "Butter-poached lobster, toasted brioche, celery, mayo.",
    price: 32,
    rating: 4.8,
    cuisine: "American",
    caloriesPerServing: 560,
    prepTime: "15 mins",
    calories: "560 Kcal",
    isFeatured: true,
    ingredients: [
      "Lobster Meat",
      "Brioche Bun",
      "Mayonnaise",
      "Celery",
      "Chives",
      "Lemon",
    ],
  },
  {
    id: 60,
    image:
      "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80",
    name: "Ramen Tonkotsu",
    description: "Rich pork broth, ramen noodles, chashu, soft egg, nori.",
    price: 19,
    rating: 4.9,
    cuisine: "Japanese",
    caloriesPerServing: 680,
    prepTime: "60 mins",
    calories: "680 Kcal",
    isFeatured: true,
    ingredients: [
      "Ramen Noodles",
      "Pork Bones",
      "Chashu",
      "Soft-Boiled Egg",
      "Nori",
      "Scallions",
      "Bamboo Shoots",
    ],
  },
];

export default Dishes;
